# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Model/'
            - '../src/Kernel.php'

    App\Domain\Repository\ReservationRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\ReservationRepository
        public: true

    App\Domain\Repository\NotificationRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\NotificationRepository
        public: true

    App\Domain\Repository\PaymentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\PaymentRepository
        public: true

    App\Domain\Repository\RestaurantRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\RestaurantRepository
        public: true

    App\Domain\Repository\ReviewRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\ReviewRepository
        public: true

    App\Domain\Repository\TableRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\TableRepository
        public: true

    App\Domain\Repository\TimeSlotRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\TimeSlotRepository
        public: true

    App\Domain\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Repository\UserRepository
        public: true

    App\Application\Service\ReservationService:
        arguments:
            $reservationRepository: '@App\Domain\Repository\ReservationRepositoryInterface'
            $tableRepository: '@App\Domain\Repository\TableRepositoryInterface'
            $timeSlotRepository: '@App\Domain\Repository\TimeSlotRepositoryInterface'
            $userRepository: '@App\Domain\Repository\UserRepositoryInterface'

    App\Application\Service\PaymentService:
        arguments:
            $paymentRepository: '@App\Domain\Repository\PaymentRepositoryInterface'
            $reservationRepository: '@App\Domain\Repository\ReservationRepositoryInterface'

    App\Application\Service\NotificationService:
        arguments:
            $notificationRepository: '@App\Domain\Repository\NotificationRepositoryInterface'
            $userRepository: '@App\Domain\Repository\UserRepositoryInterface'

    App\Application\Service\UserService:
        arguments:
            $userRepository: '@App\Domain\Repository\UserRepositoryInterface'
            $reservationRepository: '@App\Domain\Repository\ReservationRepositoryInterface'
            $reviewRepository: '@App\Domain\Repository\ReviewRepositoryInterface'
            $notificationRepository: '@App\Domain\Repository\NotificationRepositoryInterface'
            $passwordHasher: '@security.password_hasher'

    App\Application\Service\RestaurantService:
        arguments:
            $restaurantRepository: '@App\Domain\Repository\RestaurantRepositoryInterface'
            $tableRepository: '@App\Domain\Repository\TableRepositoryInterface'
            $reviewRepository: '@App\Domain\Repository\ReviewRepositoryInterface'

    App\Application\Service\ReviewService:
        arguments:
            $reviewRepository: '@App\Domain\Repository\ReviewRepositoryInterface'
            $restaurantRepository: '@App\Domain\Repository\RestaurantRepositoryInterface'
            $userRepository: '@App\Domain\Repository\UserRepositoryInterface'

    App\Application\Service\TimeSlotService:
        arguments:
            $timeSlotRepository: '@App\Domain\Repository\TimeSlotRepositoryInterface'
            $restaurantRepository: '@App\Domain\Repository\RestaurantRepositoryInterface'

    App\Application\Service\TableService:
        arguments:
            $tableRepository: '@App\Domain\Repository\TableRepositoryInterface'
            $restaurantRepository: '@App\Domain\Repository\RestaurantRepositoryInterface'